version: '3.4'

services:
  tbcacademydemo:
    image: ${DOCKER_REGISTRY-}tbcacademydemo
    build:
      context: .
      dockerfile: TbcAcademyDemo/Dockerfile

  distributedcache:
    image: redis:latest